[2024-02-05T15:07:25.702+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 1_first.first_task scheduled__2024-02-04T00:00:00+00:00 [queued]>
[2024-02-05T15:07:25.720+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 1_first.first_task scheduled__2024-02-04T00:00:00+00:00 [queued]>
[2024-02-05T15:07:25.722+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-05T15:07:25.748+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): first_task> on 2024-02-04 00:00:00+00:00
[2024-02-05T15:07:25.753+0000] {standard_task_runner.py:60} INFO - Started process 1288 to run task
[2024-02-05T15:07:25.758+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '1_first', 'first_task', 'scheduled__2024-02-04T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/1_first.py', '--cfg-path', '/tmp/tmpfjtw8z9z']
[2024-02-05T15:07:25.761+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask first_task
[2024-02-05T15:07:25.833+0000] {task_command.py:423} INFO - Running <TaskInstance: 1_first.first_task scheduled__2024-02-04T00:00:00+00:00 [running]> on host 22d288d10263
[2024-02-05T15:07:25.944+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cardthp' AIRFLOW_CTX_DAG_ID='1_first' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-04T00:00:00+00:00'
[2024-02-05T15:07:25.946+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-05T15:07:25.948+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'hey, this is the first task!']
[2024-02-05T15:07:25.958+0000] {subprocess.py:86} INFO - Output:
[2024-02-05T15:07:25.960+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: hey,: command not found
[2024-02-05T15:07:25.961+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-02-05T15:07:25.974+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-02-05T15:07:25.979+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=1_first, task_id=first_task, execution_date=20240204T000000, start_date=20240205T150725, end_date=20240205T150725
[2024-02-05T15:07:25.998+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 1288)
[2024-02-05T15:07:26.011+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-05T15:07:26.052+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-05T15:20:54.056+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 1_first.first_task scheduled__2024-02-04T00:00:00+00:00 [queued]>
[2024-02-05T15:20:54.078+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 1_first.first_task scheduled__2024-02-04T00:00:00+00:00 [queued]>
[2024-02-05T15:20:54.079+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-05T15:20:54.108+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): first_task> on 2024-02-04 00:00:00+00:00
[2024-02-05T15:20:54.116+0000] {standard_task_runner.py:60} INFO - Started process 1650 to run task
[2024-02-05T15:20:54.122+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '1_first', 'first_task', 'scheduled__2024-02-04T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/1_first.py', '--cfg-path', '/tmp/tmpa609ub85']
[2024-02-05T15:20:54.128+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask first_task
[2024-02-05T15:20:54.234+0000] {task_command.py:423} INFO - Running <TaskInstance: 1_first.first_task scheduled__2024-02-04T00:00:00+00:00 [running]> on host 22d288d10263
[2024-02-05T15:20:54.399+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cardthp' AIRFLOW_CTX_DAG_ID='1_first' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-04T00:00:00+00:00'
[2024-02-05T15:20:54.401+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-05T15:20:54.402+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, this is the first task!']
[2024-02-05T15:20:54.415+0000] {subprocess.py:86} INFO - Output:
[2024-02-05T15:20:54.417+0000] {subprocess.py:93} INFO - hey, this is the first task!
[2024-02-05T15:20:54.418+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-02-05T15:20:54.461+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=1_first, task_id=first_task, execution_date=20240204T000000, start_date=20240205T152054, end_date=20240205T152054
[2024-02-05T15:20:54.495+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-05T15:20:54.529+0000] {taskinstance.py:3280} INFO - 2 downstream tasks scheduled from follow-on schedule check
