[2024-02-05T15:07:25.474+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 1_first.first_task scheduled__2024-02-02T00:00:00+00:00 [queued]>
[2024-02-05T15:07:25.487+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 1_first.first_task scheduled__2024-02-02T00:00:00+00:00 [queued]>
[2024-02-05T15:07:25.488+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-05T15:07:25.513+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): first_task> on 2024-02-02 00:00:00+00:00
[2024-02-05T15:07:25.519+0000] {standard_task_runner.py:60} INFO - Started process 1284 to run task
[2024-02-05T15:07:25.525+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '1_first', 'first_task', 'scheduled__2024-02-02T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/1_first.py', '--cfg-path', '/tmp/tmptqqujfyo']
[2024-02-05T15:07:25.528+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask first_task
[2024-02-05T15:07:25.601+0000] {task_command.py:423} INFO - Running <TaskInstance: 1_first.first_task scheduled__2024-02-02T00:00:00+00:00 [running]> on host 22d288d10263
[2024-02-05T15:07:25.721+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cardthp' AIRFLOW_CTX_DAG_ID='1_first' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-02T00:00:00+00:00'
[2024-02-05T15:07:25.724+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-05T15:07:25.725+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'hey, this is the first task!']
[2024-02-05T15:07:25.737+0000] {subprocess.py:86} INFO - Output:
[2024-02-05T15:07:25.740+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: hey,: command not found
[2024-02-05T15:07:25.741+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-02-05T15:07:25.755+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-02-05T15:07:25.760+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=1_first, task_id=first_task, execution_date=20240202T000000, start_date=20240205T150725, end_date=20240205T150725
[2024-02-05T15:07:25.777+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task first_task (Bash command failed. The command returned a non-zero exit code 127.; 1284)
[2024-02-05T15:07:25.818+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-05T15:07:25.852+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-05T15:20:53.804+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 1_first.first_task scheduled__2024-02-02T00:00:00+00:00 [queued]>
[2024-02-05T15:20:53.828+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 1_first.first_task scheduled__2024-02-02T00:00:00+00:00 [queued]>
[2024-02-05T15:20:53.829+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-05T15:20:53.857+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): first_task> on 2024-02-02 00:00:00+00:00
[2024-02-05T15:20:53.863+0000] {standard_task_runner.py:60} INFO - Started process 1647 to run task
[2024-02-05T15:20:53.867+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '1_first', 'first_task', 'scheduled__2024-02-02T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/1_first.py', '--cfg-path', '/tmp/tmpv9_mnawd']
[2024-02-05T15:20:53.871+0000] {standard_task_runner.py:88} INFO - Job 19: Subtask first_task
[2024-02-05T15:20:53.958+0000] {task_command.py:423} INFO - Running <TaskInstance: 1_first.first_task scheduled__2024-02-02T00:00:00+00:00 [running]> on host 22d288d10263
[2024-02-05T15:20:54.100+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cardthp' AIRFLOW_CTX_DAG_ID='1_first' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-02T00:00:00+00:00'
[2024-02-05T15:20:54.102+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-05T15:20:54.105+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, this is the first task!']
[2024-02-05T15:20:54.122+0000] {subprocess.py:86} INFO - Output:
[2024-02-05T15:20:54.125+0000] {subprocess.py:93} INFO - hey, this is the first task!
[2024-02-05T15:20:54.127+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-02-05T15:20:54.171+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=1_first, task_id=first_task, execution_date=20240202T000000, start_date=20240205T152053, end_date=20240205T152054
[2024-02-05T15:20:54.241+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-05T15:20:54.283+0000] {taskinstance.py:3280} INFO - 2 downstream tasks scheduled from follow-on schedule check
